# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FitxaUrban 2.0
                                 A QGIS plugin
 Fitxa urbanística
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2019 by PSIG
        email                : admin@psig.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FitxaUrban class from file FitxaUrban.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .FitxaUrban import FitxaUrban

    # Construct the plugin
    plugin = FitxaUrban(iface)

    # Add plugin project change triggers
    iface.projectRead.connect(plugin.Preparar)
    iface.newProjectCreated.connect(plugin.Preparar)

    # return the plugin
    return plugin
    
