# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fonts\FitxaUrban_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FitxaUrbanDialog(object):
    def setupUi(self, FitxaUrbanDialog):
        FitxaUrbanDialog.setObjectName("FitxaUrbanDialog")
        FitxaUrbanDialog.setWindowModality(QtCore.Qt.WindowModal)
        FitxaUrbanDialog.resize(473, 628)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FitxaUrbanDialog.sizePolicy().hasHeightForWidth())
        FitxaUrbanDialog.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        FitxaUrbanDialog.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        FitxaUrbanDialog.setFont(font)
        FitxaUrbanDialog.setWindowOpacity(10.0)
        FitxaUrbanDialog.setAutoFillBackground(True)
        FitxaUrbanDialog.setSizeGripEnabled(False)
        FitxaUrbanDialog.setModal(True)
        self.lblTitle = QtWidgets.QLabel(FitxaUrbanDialog)
        self.lblTitle.setGeometry(QtCore.QRect(260, 20, 201, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(90, 90, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        self.lblTitle.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.gbUbicacio = QtWidgets.QGroupBox(FitxaUrbanDialog)
        self.gbUbicacio.setGeometry(QtCore.QRect(10, 70, 451, 121))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.gbUbicacio.setFont(font)
        self.gbUbicacio.setObjectName("gbUbicacio")
        self.btnParcelaPdf = QtWidgets.QPushButton(self.gbUbicacio)
        self.btnParcelaPdf.setGeometry(QtCore.QRect(350, 20, 91, 26))
        self.btnParcelaPdf.setObjectName("btnParcelaPdf")
        self.label = QtWidgets.QLabel(self.gbUbicacio)
        self.label.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.gbUbicacio)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.gbUbicacio)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_3.setObjectName("label_3")
        self.refcat = QtWidgets.QLineEdit(self.gbUbicacio)
        self.refcat.setEnabled(False)
        self.refcat.setGeometry(QtCore.QRect(130, 30, 131, 20))
        self.refcat.setObjectName("refcat")
        self.area = QtWidgets.QLineEdit(self.gbUbicacio)
        self.area.setEnabled(False)
        self.area.setGeometry(QtCore.QRect(130, 60, 81, 20))
        self.area.setObjectName("area")
        self.label_8 = QtWidgets.QLabel(self.gbUbicacio)
        self.label_8.setGeometry(QtCore.QRect(220, 60, 31, 21))
        self.label_8.setObjectName("label_8")
        self.txtAdreca = QtWidgets.QLineEdit(self.gbUbicacio)
        self.txtAdreca.setEnabled(False)
        self.txtAdreca.setGeometry(QtCore.QRect(130, 90, 316, 20))
        self.txtAdreca.setObjectName("txtAdreca")
        self.gbZones = QtWidgets.QGroupBox(FitxaUrbanDialog)
        self.gbZones.setGeometry(QtCore.QRect(10, 360, 451, 161))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.gbZones.setFont(font)
        self.gbZones.setObjectName("gbZones")
        self.label_4 = QtWidgets.QLabel(self.gbZones)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 51, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.gbZones)
        self.label_6.setGeometry(QtCore.QRect(170, 20, 141, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.gbZones)
        self.label_7.setGeometry(QtCore.QRect(90, 20, 61, 21))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.txtClau_1 = QtWidgets.QLineEdit(self.gbZones)
        self.txtClau_1.setEnabled(False)
        self.txtClau_1.setGeometry(QtCore.QRect(20, 40, 51, 20))
        self.txtClau_1.setObjectName("txtClau_1")
        self.txtPer_1 = QtWidgets.QLineEdit(self.gbZones)
        self.txtPer_1.setEnabled(False)
        self.txtPer_1.setGeometry(QtCore.QRect(90, 40, 60, 20))
        self.txtPer_1.setObjectName("txtPer_1")
        self.btnClauPdf_1 = QtWidgets.QPushButton(self.gbZones)
        self.btnClauPdf_1.setGeometry(QtCore.QRect(350, 20, 91, 26))
        self.btnClauPdf_1.setObjectName("btnClauPdf_1")
        self.txtClau_2 = QtWidgets.QLineEdit(self.gbZones)
        self.txtClau_2.setEnabled(False)
        self.txtClau_2.setGeometry(QtCore.QRect(20, 70, 51, 20))
        self.txtClau_2.setObjectName("txtClau_2")
        self.txtClau_3 = QtWidgets.QLineEdit(self.gbZones)
        self.txtClau_3.setEnabled(False)
        self.txtClau_3.setGeometry(QtCore.QRect(20, 100, 51, 20))
        self.txtClau_3.setObjectName("txtClau_3")
        self.lblOrd_1 = QtWidgets.QLabel(self.gbZones)
        self.lblOrd_1.setGeometry(QtCore.QRect(170, 40, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblOrd_1.setFont(font)
        self.lblOrd_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblOrd_1.setMouseTracking(True)
        self.lblOrd_1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblOrd_1.setObjectName("lblOrd_1")
        self.txtPer_2 = QtWidgets.QLineEdit(self.gbZones)
        self.txtPer_2.setEnabled(False)
        self.txtPer_2.setGeometry(QtCore.QRect(90, 70, 60, 20))
        self.txtPer_2.setObjectName("txtPer_2")
        self.txtPer_3 = QtWidgets.QLineEdit(self.gbZones)
        self.txtPer_3.setEnabled(False)
        self.txtPer_3.setGeometry(QtCore.QRect(90, 100, 60, 20))
        self.txtPer_3.setObjectName("txtPer_3")
        self.lblOrd_2 = QtWidgets.QLabel(self.gbZones)
        self.lblOrd_2.setGeometry(QtCore.QRect(170, 70, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblOrd_2.setFont(font)
        self.lblOrd_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblOrd_2.setMouseTracking(True)
        self.lblOrd_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblOrd_2.setObjectName("lblOrd_2")
        self.lblOrd_3 = QtWidgets.QLabel(self.gbZones)
        self.lblOrd_3.setGeometry(QtCore.QRect(170, 100, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblOrd_3.setFont(font)
        self.lblOrd_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblOrd_3.setMouseTracking(True)
        self.lblOrd_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblOrd_3.setObjectName("lblOrd_3")
        self.txtClau_4 = QtWidgets.QLineEdit(self.gbZones)
        self.txtClau_4.setEnabled(False)
        self.txtClau_4.setGeometry(QtCore.QRect(20, 130, 51, 20))
        self.txtClau_4.setObjectName("txtClau_4")
        self.txtPer_4 = QtWidgets.QLineEdit(self.gbZones)
        self.txtPer_4.setEnabled(False)
        self.txtPer_4.setGeometry(QtCore.QRect(90, 130, 60, 20))
        self.txtPer_4.setObjectName("txtPer_4")
        self.lblOrd_4 = QtWidgets.QLabel(self.gbZones)
        self.lblOrd_4.setGeometry(QtCore.QRect(170, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblOrd_4.setFont(font)
        self.lblOrd_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblOrd_4.setMouseTracking(True)
        self.lblOrd_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblOrd_4.setObjectName("lblOrd_4")
        self.gbAnnex = QtWidgets.QGroupBox(FitxaUrbanDialog)
        self.gbAnnex.setGeometry(QtCore.QRect(10, 530, 451, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.gbAnnex.setFont(font)
        self.gbAnnex.setObjectName("gbAnnex")
        self.lblCondGenerals = QtWidgets.QLabel(self.gbAnnex)
        self.lblCondGenerals.setGeometry(QtCore.QRect(10, 20, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblCondGenerals.setFont(font)
        self.lblCondGenerals.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblCondGenerals.setMouseTracking(True)
        self.lblCondGenerals.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblCondGenerals.setObjectName("lblCondGenerals")
        self.lblParamFinca = QtWidgets.QLabel(self.gbAnnex)
        self.lblParamFinca.setGeometry(QtCore.QRect(280, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblParamFinca.setFont(font)
        self.lblParamFinca.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblParamFinca.setMouseTracking(True)
        self.lblParamFinca.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblParamFinca.setObjectName("lblParamFinca")
        self.lblParamEdificacio = QtWidgets.QLabel(self.gbAnnex)
        self.lblParamEdificacio.setGeometry(QtCore.QRect(280, 40, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblParamEdificacio.setFont(font)
        self.lblParamEdificacio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblParamEdificacio.setMouseTracking(True)
        self.lblParamEdificacio.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblParamEdificacio.setObjectName("lblParamEdificacio")
        self.lblDotacioAparc = QtWidgets.QLabel(self.gbAnnex)
        self.lblDotacioAparc.setGeometry(QtCore.QRect(10, 40, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblDotacioAparc.setFont(font)
        self.lblDotacioAparc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblDotacioAparc.setMouseTracking(True)
        self.lblDotacioAparc.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblDotacioAparc.setObjectName("lblDotacioAparc")
        self.lblRegulacioAparc = QtWidgets.QLabel(self.gbAnnex)
        self.lblRegulacioAparc.setGeometry(QtCore.QRect(10, 60, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblRegulacioAparc.setFont(font)
        self.lblRegulacioAparc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblRegulacioAparc.setMouseTracking(True)
        self.lblRegulacioAparc.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblRegulacioAparc.setObjectName("lblRegulacioAparc")
        self.label_5 = QtWidgets.QLabel(FitxaUrbanDialog)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 231, 50))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("img/ESC0401.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gbSector = QtWidgets.QGroupBox(FitxaUrbanDialog)
        self.gbSector.setGeometry(QtCore.QRect(10, 200, 451, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbSector.setFont(font)
        self.gbSector.setObjectName("gbSector")
        self.txtSector = QtWidgets.QLineEdit(self.gbSector)
        self.txtSector.setEnabled(False)
        self.txtSector.setGeometry(QtCore.QRect(130, 20, 316, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtSector.setFont(font)
        self.txtSector.setObjectName("txtSector")
        self.lblSector = QtWidgets.QLabel(self.gbSector)
        self.lblSector.setGeometry(QtCore.QRect(250, 45, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblSector.setFont(font)
        self.lblSector.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblSector.setMouseTracking(True)
        self.lblSector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblSector.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSector.setObjectName("lblSector")
        self.label_9 = QtWidgets.QLabel(self.gbSector)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_9.setObjectName("label_9")
        self.gbClass = QtWidgets.QGroupBox(FitxaUrbanDialog)
        self.gbClass.setGeometry(QtCore.QRect(10, 280, 451, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gbClass.setFont(font)
        self.gbClass.setObjectName("gbClass")
        self.txtClass = QtWidgets.QLineEdit(self.gbClass)
        self.txtClass.setEnabled(False)
        self.txtClass.setGeometry(QtCore.QRect(130, 20, 316, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtClass.setFont(font)
        self.txtClass.setObjectName("txtClass")
        self.lblClass = QtWidgets.QLabel(self.gbClass)
        self.lblClass.setGeometry(QtCore.QRect(210, 45, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(False)
        self.lblClass.setFont(font)
        self.lblClass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblClass.setMouseTracking(True)
        self.lblClass.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lblClass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblClass.setObjectName("lblClass")
        self.label_11 = QtWidgets.QLabel(self.gbClass)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_11.setObjectName("label_11")
        self.Sortir = QtWidgets.QPushButton(FitxaUrbanDialog)
        self.Sortir.setGeometry(QtCore.QRect(440, 0, 31, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.Sortir.setFont(font)
        self.Sortir.setAutoDefault(False)
        self.Sortir.setObjectName("Sortir")

        self.retranslateUi(FitxaUrbanDialog)
        QtCore.QMetaObject.connectSlotsByName(FitxaUrbanDialog)

    def retranslateUi(self, FitxaUrbanDialog):
        _translate = QtCore.QCoreApplication.translate
        FitxaUrbanDialog.setWindowTitle(_translate("FitxaUrbanDialog", "FitxaUrban 2.0"))
        self.lblTitle.setText(_translate("FitxaUrbanDialog", "Fitxa urbanística"))
        self.gbUbicacio.setTitle(_translate("FitxaUrbanDialog", "Ubicació (dades cadastrals)"))
        self.btnParcelaPdf.setText(_translate("FitxaUrbanDialog", "Obrir PDF"))
        self.label.setText(_translate("FitxaUrbanDialog", "Ref. cadastral:"))
        self.label_2.setText(_translate("FitxaUrbanDialog", "Àrea:"))
        self.label_3.setText(_translate("FitxaUrbanDialog", "Adreça:"))
        self.label_8.setText(_translate("FitxaUrbanDialog", "<html><head/><body><p>m²</p></body></html>"))
        self.gbZones.setTitle(_translate("FitxaUrbanDialog", "Zones planejament"))
        self.label_4.setText(_translate("FitxaUrbanDialog", "Clau"))
        self.label_6.setText(_translate("FitxaUrbanDialog", "Tipus ordenació"))
        self.label_7.setText(_translate("FitxaUrbanDialog", "%"))
        self.btnClauPdf_1.setText(_translate("FitxaUrbanDialog", "Obrir PDF"))
        self.lblOrd_1.setText(_translate("FitxaUrbanDialog", "<a href=\'condicions_generals.htm\'>ORD</a>"))
        self.lblOrd_2.setText(_translate("FitxaUrbanDialog", "<a href=\'condicions_generals.htm\'>ORD</a>"))
        self.lblOrd_3.setText(_translate("FitxaUrbanDialog", "<a href=\'condicions_generals.htm\'>ORD</a>"))
        self.lblOrd_4.setText(_translate("FitxaUrbanDialog", "<a href=\'condicions_generals.htm\'>ORD</a>"))
        self.gbAnnex.setTitle(_translate("FitxaUrbanDialog", "Annex"))
        self.lblCondGenerals.setText(_translate("FitxaUrbanDialog", "<a href=\'condicions_generals.htm\'>Condicions Generals</a>"))
        self.lblParamFinca.setText(_translate("FitxaUrbanDialog", "<a href=\'param_finca.htm\'>Paràmetres Finca</a>"))
        self.lblParamEdificacio.setText(_translate("FitxaUrbanDialog", "<a href=\'param_edificacio.htm\'>Paràmetres Edificació</a>"))
        self.lblDotacioAparc.setText(_translate("FitxaUrbanDialog", "<a href=\'dotacio_aparcament.htm\'>Dotació mínima d\'aparcaments</a>"))
        self.lblRegulacioAparc.setText(_translate("FitxaUrbanDialog", "<a href=\'regulacio_aparcament.htm\'>Regulació particular de l\'ús d\'aparcaments</a>"))
        self.gbSector.setTitle(_translate("FitxaUrbanDialog", "Sector"))
        self.lblSector.setText(_translate("FitxaUrbanDialog", "<a href=\'condicions_generals.htm\'>Veure Normativa sector</a>"))
        self.label_9.setText(_translate("FitxaUrbanDialog", "Codi - Nom:"))
        self.gbClass.setTitle(_translate("FitxaUrbanDialog", "Classificació"))
        self.lblClass.setText(_translate("FitxaUrbanDialog", "<a href=\'condicions_generals.htm\'>Veure Normativa classificació</a>"))
        self.label_11.setText(_translate("FitxaUrbanDialog", "Codi - Nom:"))
        self.Sortir.setText(_translate("FitxaUrbanDialog", "x"))

